# -*- coding: utf-8 -*-
"""Hafta7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDMeEj1aJBSzWxi2frBTdnOdmE6Kv2W9
"""

def selam():
  print("Merhaba Ben ilk fonksiyon")

selam()

def toplama(a,b):
  toplam = a+b
  #print(toplam)
  return toplam

#toplama(4,3)
sayı1 = int(input("Birinci Sayıyı Gir:"))
sayı2 = int(input("İkinci Sayıyı Gir:"))

sonuc = toplama(sayı1,sayı2)

if (sonuc > 0):
  print("Sonuc pozitif")
elif (sonuc <0):
  print("Sonuc Negatif")
else:
  print("Sonuc Sıfırdır")

def toplama(*sayilar):
  toplam = 0
  for sayi in sayilar:
    toplam += sayi
  print("Sayıların Toplamı:{}".format(toplam))

toplama(5234,543234,345)

toplama(123,4)

toplama(423,423,523,-23)

def bilgigoster(isim="Boş",soyisim="Boş",Yas="Boş",Tel="Boş"):
  print("\nİsim:",isim,"\nSoyisim:",soyisim,"\nYaş:",Yas,"\nTelefon:",Tel)

ad = input("İsim Gir:")
soyad = input("Soyisim Gir:")
yas = input("Yaşınız:")
tel = input("Telefon:")

for x in range(11):
  if x % 2 == 0:
    continue
  print(x)

bilgigoster(ad,soyad)
bilgigoster()
bilgigoster(ad,soyad,yas,tel)

for sayi in range(10,0,-1):
  print('sıradaki sayı',sayi)

def fonksiyon():
  def fonksiyon2():
    print("Küçük fonksiyondan Merhaba")
  print("Büyük fonksiyondan Merhaba")
  fonksiyon2()
fonksiyon()

demet = (2,3,4,5)

demet[0]

demet[0] = 6

demet2 = (3)

type(demet2)

demet3 = (3,)

type(demet3)

demet = (1,23,34,34,2,1,4,5,1,1,34)
print(demet.count(1))

demet = (3,4,5,"Yağız","Yekta","Hülya")
print(demet.index("Yekta"))

yeni_sözlük = {"bir":1,"iki":"elma","üç":"fındık"}
print(yeni_sözlük.values())
print(yeni_sözlük.keys())

a = {"bir":1,"iki":2,"üç":3}
a["dört"] = 4
print(a)

a = {"bir" : "ali", "iki": [[1,2],[3,4],[5,6]],"üç" : 15}
print(a["üç"])
a["üç"] += 5
print(a["üç"])
a["bir"] +="veli"
print(a)
print(type(a["bir"]))

sayi1 = "19" 
sayi2 = "53"
toplam = sayi1+sayi2
print(toplam*4)

liste = [23,5,7,24,71,"d","ed",4]
bolunmus_liste =liste[::2]
print(bolunmus_liste)

sayi1 = "19"
sayi2 = "53"
toplam = sayi1+sayi2
print(toplam)

print(*range(3,30,5))

i = 1
while (i < 10):
  print(i)
  if (i == 5):
    break
  i +=1

